### ISSUE TITLE
mobile settings

### ISSUE THREAD

**Issue by stephenlprice** [API-Guild/tableau-postman#65]
- [x] [Get Mobile Security Settings for Server](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_mobile_settings.htm#get_mobile_security_settings_for_server)
- [x] [Get Mobile Security Settings for Site](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_mobile_settings.htm#get_mobile_security_settings_for_site)
- [x] [Update Mobile Security Settings for Site](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_mobile_settings.htm#Update_mobile_security_settings_for_site)

**Comment by jeremymayo** [comment]
- [ ] [Get Mobile Security Settings for Server](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_mobile_settings.htm#get_mobile_security_settings_for_server)
- [ ] [Get Mobile Security Settings for Site](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_mobile_settings.htm#get_mobile_security_settings_for_site)
- [ ] [Update Mobile Security Settings for Site](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_mobile_settings.htm#Update_mobile_security_settings_for_site)
